### ISSUE TITLE
make setup syntax error

### ISSUE THREAD

**Issue by adamhstewart** [mariano-dagostino/drock#1]
On the `make setup` command on OSX I get this error

````bash
Adams-MacBook-Pro-4:jep-container adamstewart$ make setup
Downloading Laradock...
Laradock 5.9.0 downloaded
sed: 1: "/# Clean up/ iUSER root ...": command i expects \ followed by text
make: *** [fys/.env] Error 1
````

which seems to be of no consequence,

**Comment by adamhstewart** [comment]
@mariano-dagostino This is not inconsequential.

Mac OSX has a different version of `sed` which requires file extensions when using the `-i` option.

The easiest fix is to install the GNU version of `sed` using homebrew:

`brew install gnu-sed --with-default-names`

The option flag there allows it to be run with the `sed` command rather that `gsed`.

**Comment by mariano-dagostino** [comment]
Thanks!. Documented in the README.
